### ISSUE TITLE
rip

### ISSUE THREAD

**Issue by lxi1400** [Not-Cyrus/GoGuardian#2]
hi Cy I got disabled and looks like U did too? 😔

**Comment by Not-Cyrus** [comment]
LOL YEP !fishgang Cy#7013

**Comment by Not-Cyrus** [comment]
issue resolved (ly2 discord)

**Comment by Not-Cyrus** [comment]
not resolved anymore

**Comment by Not-Cyrus** [comment]
!fishgang Cy#1792 @lxi1400
