### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darkside69696** [Not-Cyrus/GoGuardian#7]
How can I fix this?
![cxzcz](https://user-images.githubusercontent.com/79799411/109423824-40ff2e80-79e1-11eb-97da-6fe58295f3dd.PNG)

**Comment by darkside69696** [comment]
![cxzczx](https://user-images.githubusercontent.com/79799411/109425912-f2ef2880-79ea-11eb-8d10-3356c89e1582.PNG)

**Comment by lxi1400** [comment]
the issue is legit right in ur face

**Comment by darkside69696** [comment]
=[[

**Comment by Not-Cyrus** [comment]
delete the discordgo version from your gopath (I'm currently on phone or I would write how) so just use Google for that if you don't know how (default path is your user directory\go)

then run this V

go get github.com/bwmarrin/discordgo@v0.22.0

**Comment by darkside69696** [comment]
![xzczx](https://user-images.githubusercontent.com/79799411/109429234-f68aab80-79fa-11eb-82a2-4666defff649.PNG)
![zxczxcz](https://user-images.githubusercontent.com/79799411/109429243-fa1e3280-79fa-11eb-803f-52565f5207cf.PNG)

**Comment by Not-Cyrus** [comment]
Did you forget to run this command?
```YAML
db.whitelist.insertOne({useless: "github.com/Not-Cyrus"})
```

**Comment by darkside69696** [comment]
![sdada](https://user-images.githubusercontent.com/79799411/109429979-20de6800-79ff-11eb-86f9-31cced5c7974.PNG)
hmm I got this message

**Comment by Not-Cyrus** [comment]
now you can run the bot again and it should work

**Comment by darkside69696** [comment]
ok, ty, can I host it on repl.it?

**Comment by Not-Cyrus** [comment]
I've never tried before, so you might but I would never recommend hosting on repl.it (coming from someone making a repl.it scraper right now lol)

**Comment by darkside69696** [comment]
hmm, do you know a good vps ?

**Comment by Not-Cyrus** [comment]
Digital Ocean is a decent one, but you'll have to do research on your own to see what fits your needs (I personally just self host)

**Comment by lxi1400** [comment]
kys

**Comment by kaihgg** [comment]
same

**Comment by Not-Cyrus** [comment]
closed as it's been almost 24 hours, issue seems fixed.

**Comment by unrapeable** [comment]
@darkside69696 how were u even able to run it on repl
