### ISSUE TITLE
som

### ISSUE THREAD

**Issue by unrapeable** [Not-Cyrus/GoGuardian#8]
![image](https://user-images.githubusercontent.com/73660095/109583068-e50dd600-7ac4-11eb-8ff6-998856a84625.png)

why does this happen

**Comment by kaihgg** [comment]
> ![image](https://user-images.githubusercontent.com/73660095/109583068-e50dd600-7ac4-11eb-8ff6-998856a84625.png)
> 
> why does this happen

u are using repl.it use ur cmd prompt

**Comment by unrapeable** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/73660095/109583068-e50dd600-7ac4-11eb-8ff6-998856a84625.png)
> > why does this happen
> 
> u are using repl.it use ur cmd prompt

dang i was tryna host it on repl cuz me no money

**Comment by Not-Cyrus** [comment]
try redownloading it, also I wouldn't recommend hosting it on repl.it 

Reason: https://github.com/Not-Cyrus/repl.it-scraper

**Comment by unrapeable** [comment]
> try redownloading it, also I wouldn't recommend hosting it on repl.it
> 
> Reason: https://github.com/Not-Cyrus/repl.it-scraper

i have a hacker plan already so

**Comment by unrapeable** [comment]
@Not-Cyrus btw how can i host it on heroku

**Comment by Not-Cyrus** [comment]
I've never personally done it

**Comment by unrapeable** [comment]
> I've never personally done it

will u be able to add a config so the bot can auto login

**Comment by Not-Cyrus** [comment]
oops I accidentally closed it, but I did the token login how it is on purpose. So no, I will not be making a configuration file.

**Comment by unrapeable** [comment]
> oops I accidentally closed it, but I did the token login how it is on purpose. So no, I will not be making a configuration file.

oh okay i was just wondering since heroku doesnt let you type in the logs so i cant paste the token.

**Comment by Not-Cyrus** [comment]
you could hard-code it on line 64
```go
var (
	bot    = api.Bot{}
	dshard int
	token  string = "yourtoken"
)
```

and remove these 2 lines

```go
fmt.Print("Enter your token: ")
fmt.Scan(&token)
```
on line 17,18

**Comment by unrapeable** [comment]
> you could hard-code the token by changing these 2 (main.go)
> 
> ```go
> var (
> 	bot    = api.Bot{}
> 	dshard int
> 	token  string = "yourtoken" // line 64
> )
> ```
> 
> ```go
> fmt.Print("Enter your token: ") // line 17
> fmt.Scan(&token) // line 18
> ```

okay so the login works now and what about the shards

**Comment by unrapeable** [comment]
nvm i was able to figure it out thanks for ur help :)

**Comment by unrapeable** [comment]
well i figured out how to do it on the shards but heroku then says 
![image](https://user-images.githubusercontent.com/73660095/110058241-9d3ab900-7d27-11eb-8662-ea1c1ee1cca9.png)

**Comment by Not-Cyrus** [comment]
No clue what that error is, must be something with heroku

**Comment by Not-Cyrus** [comment]
Closed as it's been 2 days since last response (not including my own)

**Comment by unrapeable** [comment]
> 
> 
> Closed as it's been 2 days since last response (not including my own)

yea i didnt find a fix
